
export const todosTypes = {
    START_FETCHING: "START_FETCHING",
    END_FETCHING: "END_FETCHING",
    IS_ERROR: "IS_ERROR",
    TOGGLE_TODO: "TOGGLE_TODO",
    DELETE_TODO: "DELETE_TODO",
    ADD_TODO: "ADD_TODO",
    ADD_IMPORTANT_TODO: "ADD_IMPORTANT_TODO",
    TOGGLE_URGENT_TODO: "TOGGLE_URGENT_TODO",
}